### ISSUE TITLE
License compliance issue

### ISSUE THREAD

**Issue by wez** [o2sh/miro#1]
Hello!  I'm pleased that you found the code in https://github.com/wez/wezterm useful and were able to build something of your own from it, but one of the conditions of the [license](https://github.com/wez/wezterm/blob/main/LICENSE.md) is that you include the license notice and, importantly, my copyright, in the work that you derive from it.

Please update your license file to reflect that this project uses code that is Copyright 2018-2021 Wez Furlong.

Thanks!

**Comment by o2sh** [comment]
Sure thing, a095cff should cover it.
Thanks a lot for the amazing work that you've done, it saved me a lot of time.

**Comment by wez** [comment]
Thanks, and thanks!
