### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by mmdbalkhi** [o2sh/miro#19]
https://github.com/o2sh/miro/blob/15a05c14bd22e79382790197181105e5321eefc7/src/font/hbwrap.rs#L22

Hello. Your program is excellent and I really understood the power of rust with this app. I got an error while compiling the program:

```bash
➜  miro git:(main) make install
cargo install --path "."
Installing miro v0.2.0 (/home/mmdbalkhi/w/miro)
Updating crates.io index
Updating git repository `https://github.com/o2sh/xkbcommon-rs.git`
Compiling libc v0.2.119
.
.
.
Compiling zstd v0.6.1+zstd.1.4.9
error: 1 positional argument in format string, but no arguments were given
  --> src/font/hbwrap.rs:22:53
   |
22 |         ensure!(!lang.is_null(), "failed to convert {} to language");
   |                                                     ^^

error: failed to compile `miro v0.2.0 (/home/mmdbalkhi/w/miro)`, intermediate artifacts can be found at `/home/mmdbalkhi/w/miro/target`

Caused by:
  could not compile `miro` due to previous error
make: *** [Makefile:2: install] Error 101

```

Of course, I do not think this bug has not been detected for a year. For this reason, I suspect that this problem is due to different versions of libraries and rust.

- rustc: rustc 1.59.0 (Arch Linux rust 1:1.59.0-1)
- cargo: cargo 1.59.0

To solve this problem, I also opened a pr ( #18 ).

**Comment by o2sh** [comment]
Hi @mmdbalkhi, sorry for the late answer.

Are you still having trouble compiling the program ?

**Comment by mmdbalkhi** [comment]
> Hi @mmdbalkhi, sorry for the late answer.
> 
> Are you still having trouble compiling the program ?

Hello @o2sh, Thanks for the reply. No, I did not see any error after solving that minor problem.
