### ISSUE TITLE
curious

### ISSUE THREAD

**Issue by pjhalsli** [o2sh/miro#2]
Saw your video on reddit beofre you took it down and it made me curios.

I use Arch tho so none of the libraries needed are to find in Arch - they might ofc have some other name. The same problem with cargo build. I found 20 different  cargo programs but none called only cargo. I would like to figure this out and give this thing a spin. _I'm not a programmer - merely an enthusiast - so any help or pointing in the correct direction would be highly appreciated

I found cargo was included in the rust pkg so that problem is now solved . I'm building right now but excited as I didn't install any of the libs needed,

**Comment by o2sh** [comment]
Hi @pjhalsli,
cargo is part of the Rust toolchain, I updated the [README](https://github.com/o2sh/miro#building-from-source) with more details + Arch deps. 
I couldn't test it however (I only run Ubuntu), so plz report back if it doesn't work.

**Comment by pjhalsli** [comment]
I got it to work fine- now trying to firgureo ut how to make the font bigger - on a 4k screen they fonts are brely visible as you can see here
https://imgur.com/a/bRHka5i

**Comment by o2sh** [comment]
@pjhalsli, a rescaling based on the screen dpi was added, hopefully it will solve your issue.
