### ISSUE TITLE
Can miro run on MacOS?

### ISSUE THREAD

**Issue by Monster12138** [o2sh/miro#4]
Build failed in MacOS11.0.
![image](https://user-images.githubusercontent.com/31857315/109595192-fdc2ce00-7b4e-11eb-9ae0-2d25092bb23b.png)

**Comment by o2sh** [comment]
Support for MacOS is in progress :100: 
As of now miro only runs on Linux with XCB and OpenGL ES 2.

**Comment by o2sh** [comment]
MacOS is now supported:

![lll](https://user-images.githubusercontent.com/13710835/110845581-18154e00-82ab-11eb-99d3-92edad8b313b.gif)
