### ISSUE TITLE
Miro opens for half a second then closes

### ISSUE THREAD

**Issue by ThatOneCalculator** [o2sh/miro#5]
Command run: `cargo run`

Output:
- Miro runs for half a second then closes
- 
```
 warning: 7 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 15.34s
     Running `target/debug/miro`
shm_available: false
picked visual 21, screen root visual is 21
trying libEGL.so.1
initialized EGL version 1.5
thread 'main' panicked at 'range end index 64 out of range for slice of length 60', src/frontend/gui/quad.rs:55:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ThatOneCalculator** [comment]
Same thing happens when I run `target/debug/miro`

**Comment by ThatOneCalculator** [comment]
Perhaps it was my CPU usage, because after I stopped doing some CPU intensive activity (compiling my kernel), it opened fine

**Comment by o2sh** [comment]
Sorry about that, I was forcing the CPU load to be 2 digits.

with 61f7820, it can range from 0 to 100.

Thanks for reporting the issue @ThatOneCalculator
