### ISSUE TITLE
we're confused about the screen size?

### ISSUE THREAD

**Issue by dragonnn** [o2sh/miro#7]
Hi, I am getting this error when starting miro:
```
thread 'main' panicked at 'failed to paint screen: ErrorMessage { msg: "we\'re confused about the screen size" }', src/gui/window.rs:311:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
I add some more info into the code: 
```
thread 'main' panicked at 'failed to paint screen: ErrorMessage { msg: "we\'re confused about the screen size, star_pos: 7680, per_line: 320" }', src/gui/window.rs:311:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I am running a three monitor setup, so maybe this is confusing miro. xrandr output:
```
xrandr | grep connected

DP-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 531mm x 298mm
eDP-1-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
HDMI-A-1-0 connected 1920x1200+3840+0 (normal left inverted right x axis y axis) 518mm x 324mm
```
I really like the idea of having a Rust terminal :D, so would be nice to get it working. I know some Rust so I can do some testing to get it running. Thanks for any help :)

**Comment by o2sh** [comment]
Thanks for reporting the issue @dragonnn

I can't reproduce but I may have fixed it with a2b12ad.

Plz try again after pulling from HEAD.

**Comment by dragonnn** [comment]
Hmmm maybe some progress? Now it shows:
```
picked visual 21, screen root visual is 21
trying libEGL.so.1
initialized EGL version 1.5
thread 'main' panicked at 'failed to paint screen: ErrorMessage { msg: "line 24 is outside the vertex buffer range" }', src/gui/window.rs:312:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And the window seams to flash for a brief moment.

**Comment by o2sh** [comment]
maybe with 15d3f3c 😕

**Comment by dragonnn** [comment]
yes :), now it started :D. Thanks!
Can be scrooling made faster? Compared to mate-terminal I need to scrool much more when for example dumping dmesg inside the terminal.
