### ISSUE TITLE
License of sprites?

### ISSUE THREAD

**Issue by io12** [o2sh/miro#9]
This is a really cool project. I really love the animated bar at the top and want to try porting it to Emacs.

I saw this in `LICENSE`:

```
NOTICE: The sprite assets are are not covered by the LICENSE file.
```

What are the license terms for the sprites, or where did you get them from?

**Comment by o2sh** [comment]
I created them using [aseprite](https://www.aseprite.org/) based on models I found online. "Fan art" is mostly overlooked in the case of non commercial products (GPL License), but yeah I obviously don't own the rights for the characters...

**Comment by io12** [comment]
They're really good! I have a few followup questions though.

1. Even though they're not covered by the license, would you be okay with people using the art in other projects?
2. Why did you delete the Sonic and Mega Man themes?

**Comment by o2sh** [comment]
1. Sure, no problem.
2. They both were too tall resulting in an overlap with the first terminal line, I may fix it later on:

<img width="752" alt="Screenshot 2021-05-25 at 05 49 00" src="https://user-images.githubusercontent.com/13710835/119436680-edb92580-bd1c-11eb-9a9b-c80aedbbf77b.png">
<img width="752" alt="Screenshot 2021-05-25 at 05 48 44" src="https://user-images.githubusercontent.com/13710835/119436685-ef82e900-bd1c-11eb-85db-a8eb07ef9023.png">

**Comment by io12** [comment]
Thanks
